import bagel.util.Vector2;

/**
 * A class representing a Green Peg.
 * Green Pegs generate two Ball objects when struck by a Ball object.
 */

public class GreenPeg extends Peg {
    private static final String NORMAL_FILE = "res/green-peg.png";
    private static final String HORIZONTAL_FILE = "res/green-horizontal-peg.png";
    private static final String VERTICAL_FILE = "res/green-vertical-peg.png";
    private static final int NORMAL_FILE_LENGTH = 2;
    private static final int SHAPE_INDEX = 2;

    //Initial velocity for balls generated by Green Peg effect.
    private static final double INITIAL_BALL_VELOCITY = 10;

    //Determine the shape, and thus the file to obtain image from.
    //Input String is of form "<colour>_peg_<shape>"
    private static String determineShapeFile(String input) {
        if ((input.split("_")).length == NORMAL_FILE_LENGTH) {
            return NORMAL_FILE;
        } else if ((input.split("_")[SHAPE_INDEX].equals("horizontal"))) {
            return HORIZONTAL_FILE;
        } else {
            return VERTICAL_FILE;
        }
    }
    private static String determineShapeFile(Peg peg) {
        String shape = peg.getShape();
        if (shape.equals("Normal")) {
            return NORMAL_FILE;
        } else if (shape.equals("Horizontal")) {
            return HORIZONTAL_FILE;
        } else {
            return VERTICAL_FILE;
        }
    }

    /**
     * Create a Green Peg.
     * @param configuration used to determine the shape.
     * @param x x-coordinate.
     * @param y y-coordinate.
     */
    public GreenPeg(String configuration, double x, double y) {
        super(x, y, determineShapeFile(configuration));
        setShape(determineShape(configuration));
    }
    /**
     * Create a Green Peg with the shape and coordinates of an existing peg.
     * @param peg an existing peg to copy shape and coordinates from.
     */
    public GreenPeg(Peg peg) {
        super(peg.getPoint().x, peg.getPoint().y, determineShapeFile(peg));
        setShape(peg.getShape());
    }

    //Determine the shape as a string to record for future use
    private String determineShape(String input) {
        if ((input.split("_")).length == NORMAL_FILE_LENGTH) {
            return "Normal";
        } else if ((input.split("_")[SHAPE_INDEX].equals("horizontal"))) {
            return "Horizontal";
        } else {
            return "Vertical";
        }
    }

    /**
     * Generate two balls of the same type as the ball which struck the Green Peg.
     * One ball will begin with a velocity of 45 degrees to the top-left and the other 45 degrees to the top-right.
     * @param ball the original ball
     * @return array containing original ball and newly generated balls
     */
    public Ball[] generateBalls(Ball ball) {
        Ball leftBall = ball.duplicateType(this.getPoint());
        Ball rightBall = ball.duplicateType(this.getPoint());

        leftBall.setVelocity(new Vector2(-1,-1).normalised().mul(INITIAL_BALL_VELOCITY));
        rightBall.setVelocity(new Vector2(1,-1).normalised().mul(INITIAL_BALL_VELOCITY));

        return new Ball[]{ball, leftBall, rightBall};
    }
}
